"""004 - Remove purchase_history table

Revision ID: 004_remove_purchase_history
Revises: 003_refactor_flights_tickets
Create Date: 2025-11-17 15:58:13.892169

Removes the purchase_history table completely as business logic changes
to direct flight-passenger relationships via tickets.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '004_remove_purchase_history'
down_revision: Union[str, None] = '003_refactor_flights_tickets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - ajustado para CASCADE ###
    # Use execute to handle errors gracefully
    op.execute("DROP INDEX IF EXISTS ix_purchase_history_id")
    op.execute("DROP TABLE IF EXISTS purchase_history CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.create_table('purchase_history',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('status', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
        sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
        sa.Column('payment_method', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name='purchase_history_person_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='purchase_history_pkey')
    )
    op.create_index('ix_purchase_history_id', 'purchase_history', ['id'], unique=False)
    op.add_column('tickets', sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tickets_purchase_id_fkey', 'tickets', 'purchase_history', ['purchase_id'], ['id'])
    # ### end Alembic commands ###
