"""005 - Add flights metadata columns

Revision ID: 005_add_flights_metadata
Revises: 004_remove_purchase_history
Create Date: 2025-11-25 23:16:11.102741

Adds flight metadata: stops_count, avaliable_seats (total), premium_seats (premium qty).
Replaces old business_seats and first_seats with the new premium_seats field.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005_add_flights_metadata'
down_revision: Union[str, None] = '004_remove_purchase_history'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('stops_count', sa.Integer(), nullable=False))
    op.add_column('flights', sa.Column('avaliable_seats', sa.Integer(), nullable=False))
    op.add_column('flights', sa.Column('premium_seats', sa.Integer(), nullable=False))
    op.drop_column('flights', 'first_seats')
    op.drop_column('flights', 'business_seats')
    op.alter_column('seats', 'seat_class',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tickets', 'seat_class',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'seat_class',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('seats', 'seat_class',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.add_column('flights', sa.Column('business_seats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('first_seats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('flights', 'premium_seats')
    op.drop_column('flights', 'avaliable_seats')
    op.drop_column('flights', 'stops_count')
    # ### end Alembic commands ###
