"""add_seat_number_to_tickets

Revision ID: 010_add_seat_number_to_tickets
Revises: 009_add_seat_enum
Create Date: 2025-12-12 23:51:23.693031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010_add_seat_number_to_tickets'
down_revision: Union[str, None] = '009_add_seat_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('seat_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'seat_number')
    # ### end Alembic commands ###
