"""add_boarding_and_arrival_time_to_tickets

Revision ID: 011_add_boarding_arrival_time
Revises: 010_add_seat_number_to_tickets
Create Date: 2025-12-12 23:58:57.287227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011_add_boarding_arrival_time'
down_revision: Union[str, None] = '010_add_seat_number_to_tickets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('boarding_time', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.add_column('tickets', sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'arrival_time')
    op.drop_column('tickets', 'boarding_time')
    # ### end Alembic commands ###
