"""make_purchase_id_nullable

Revision ID: 012_make_purchase_id_nullable
Revises: 011_add_boarding_arrival_time
Create Date: 2025-12-13 00:00:33.949898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012_make_purchase_id_nullable'
down_revision: Union[str, None] = '011_add_boarding_arrival_time'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'purchase_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'purchase_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
