"""add_flight_booking_models

Revision ID: 677b271bf48e
Revises: b3d627dbec93
Create Date: 2025-10-10 19:46:24.201738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677b271bf48e'
down_revision: Union[str, None] = 'b3d627dbec93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'deleted', name='airline_status', native_enum=False), nullable=True),
    sa.Column('dt_create', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dt_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_airlines_id'), 'airlines', ['id'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destiny', sa.String(), nullable=False),
    sa.Column('f_class', sa.Enum('economy', 'business', 'first', name='flight_class', native_enum=False), nullable=False),
    sa.Column('departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('a_seats', sa.Integer(), nullable=False),
    sa.Column('t_seats', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'cancelled', name='flight_status', native_enum=False), nullable=True),
    sa.Column('dt_create', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dt_update', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_number')
    )
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    op.create_table('purchase_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ativas', 'planejadas', 'passadas', name='purchase_status', native_enum=False), nullable=False),
    sa.Column('destiny', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('dt_create', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dt_update', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_history_id'), 'purchase_history', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_history_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('passengers', sa.Text(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('horario_embarque', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horario_desembarque', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('marked', 'reserved', 'cancelled', 'completed', name='booking_status', native_enum=False), nullable=True),
    sa.Column('dt_create', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dt_update', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['purchase_history_id'], ['purchase_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_table('ticket_passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_passengers_id'), 'ticket_passengers', ['id'], unique=False)
    op.add_column('persons', sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'gender')
    op.drop_index(op.f('ix_ticket_passengers_id'), table_name='ticket_passengers')
    op.drop_table('ticket_passengers')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_purchase_history_id'), table_name='purchase_history')
    op.drop_table('purchase_history')
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_airlines_id'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###
