"""added flight stop counter

Revision ID: 8913b06f344c
Revises: 001_remove_purchase_id
Create Date: 2025-11-25 23:16:11.102741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8913b06f344c'
down_revision: Union[str, None] = '001_remove_purchase_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('stops_count', sa.Integer(), nullable=False))
    op.add_column('flights', sa.Column('avaliable_seats', sa.Integer(), nullable=False))
    op.add_column('flights', sa.Column('premium_seats', sa.Integer(), nullable=False))
    op.drop_column('flights', 'first_seats')
    op.drop_column('flights', 'business_seats')
    op.alter_column('seats', 'seat_class',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('economy', 'business', 'executive', 'first', name='seat_class_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('tickets', 'seat_class',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('economy', 'business', 'executive', 'first', name='seat_class', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'seat_class',
               existing_type=sa.Enum('economy', 'business', 'executive', 'first', name='seat_class', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('seats', 'seat_class',
               existing_type=sa.Enum('economy', 'business', 'executive', 'first', name='seat_class_enum', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.add_column('flights', sa.Column('business_seats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('first_seats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('flights', 'premium_seats')
    op.drop_column('flights', 'avaliable_seats')
    op.drop_column('flights', 'stops_count')
    # ### end Alembic commands ###
