"""der_update

Revision ID: 8ec4ed8b1a58
Revises: 677b271bf48e
Create Date: 2025-10-26 16:29:46.850078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ec4ed8b1a58'
down_revision: Union[str, None] = '677b271bf48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(), nullable=False),
    sa.Column('seat_class', sa.Enum('economy', 'business', 'first', name='seat_class_enum', native_enum=False), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'seat_number', name='unique_flight_seat')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_table('ticket_status_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('marked', 'reserved', 'cancelled', 'completed', name='old_status', native_enum=False), nullable=False),
    sa.Column('new_status', sa.Enum('marked', 'reserved', 'cancelled', 'completed', name='new_status', native_enum=False), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_status_log_id'), 'ticket_status_log', ['id'], unique=False)
    op.drop_index('ix_ticket_passengers_id', table_name='ticket_passengers')
    op.drop_table('ticket_passengers')
    op.add_column('airlines', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('airlines', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('airlines', 'dt_update')
    op.drop_column('airlines', 'dt_create')
    op.add_column('flights', sa.Column('aircraft_model', sa.String(), nullable=False))
    op.add_column('flights', sa.Column('origin_city', sa.String(), nullable=False))
    op.add_column('flights', sa.Column('origin_airport', sa.String(), nullable=False))
    op.add_column('flights', sa.Column('destination_city', sa.String(), nullable=False))
    op.add_column('flights', sa.Column('destination_airport', sa.String(), nullable=False))
    op.add_column('flights', sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('flights', sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=False))
    op.add_column('flights', sa.Column('economy_seats', sa.Integer(), nullable=False))
    op.add_column('flights', sa.Column('business_seats', sa.Integer(), nullable=False))
    op.add_column('flights', sa.Column('first_seats', sa.Integer(), nullable=False))
    op.add_column('flights', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('flights', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('flights', 'dt_create')
    op.drop_column('flights', 'a_seats')
    op.drop_column('flights', 'departure')
    op.drop_column('flights', 'origin')
    op.drop_column('flights', 'destiny')
    op.drop_column('flights', 'dt_update')
    op.drop_column('flights', 't_seats')
    op.drop_column('flights', 'arrival')
    op.drop_column('flights', 'f_class')
    op.add_column('persons', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('persons', sa.Column('birth_date', sa.String(), nullable=False))
    op.add_column('persons', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('persons', sa.Column('status', sa.Enum('active', 'inactive', 'deleted', name='user_status', native_enum=False), nullable=True))
    op.add_column('persons', sa.Column('person_type', sa.Enum('customer', 'company_admin', 'sysadmin', name='user_type', native_enum=False), nullable=True))
    op.add_column('persons', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('persons', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('persons', 'dt_create')
    op.drop_column('persons', 'name')
    op.drop_column('persons', 'phone')
    op.drop_column('persons', 'state')
    op.drop_column('persons', 'p_type')
    op.drop_column('persons', 'dt_birth')
    op.drop_column('persons', 'dt_update')
    op.add_column('purchase_history', sa.Column('person_id', sa.Integer(), nullable=False))
    op.add_column('purchase_history', sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('purchase_history', sa.Column('payment_method', sa.Enum('credit', 'debit', 'pix', 'cash', name='payment_method', native_enum=False), nullable=False))
    op.add_column('purchase_history', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_history', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('purchase_history', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('active', 'planned', 'past', name='purchase_status', native_enum=False),
               existing_nullable=False)
    op.drop_constraint('purchase_history_user_id_fkey', 'purchase_history', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_history', 'persons', ['person_id'], ['id'])
    op.drop_column('purchase_history', 'user_id')
    op.drop_column('purchase_history', 'dt_create')
    op.drop_column('purchase_history', 'origin')
    op.drop_column('purchase_history', 'destiny')
    op.drop_column('purchase_history', 'dt_update')
    op.add_column('tickets', sa.Column('purchase_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('passenger_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('seat_class', sa.Enum('economy', 'business', 'first', name='seat_class', native_enum=False), nullable=False))
    op.add_column('tickets', sa.Column('seat_number', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('tickets', sa.Column('boarding_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tickets', sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tickets', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('tickets_purchase_history_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'purchase_history', ['purchase_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'persons', ['passenger_id'], ['id'])
    op.drop_column('tickets', 'dt_create')
    op.drop_column('tickets', 'passengers')
    op.drop_column('tickets', 'horario_desembarque')
    op.drop_column('tickets', 'purchase_history_id')
    op.drop_column('tickets', 'valor')
    op.drop_column('tickets', 'dt_update')
    op.drop_column('tickets', 'horario_embarque')
    # Now insert the sysadmin user after all columns have been added
    op.execute("""
        INSERT INTO persons (
            id,
            cpf,
            email,
            hashed_password,
            gender,
            full_name,
            birth_date,
            phone_number,
            status,
            person_type,
            created_at,
            updated_at
        ) VALUES (
            0,
            '789.417.690-78',
            'super@admin.com',
            '$argon2id$v=19$m=65536,t=3,p=4$oFSq9f4fA0CIcW5NSendmw$lWTkgXFinVyc4BUY7oB+UpFphEF3iuB04za2HeveX7w',
            'male',
            'SA',
            '1999-12-31',
            '99999999999',
            'active',
            'sysadmin',
            '2025-10-31 15:07:23.195-04',
            '2025-10-31 15:07:23.195-04'
        );
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('horario_embarque', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('dt_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('valor', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('purchase_history_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('horario_desembarque', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('passengers', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('dt_create', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_purchase_history_id_fkey', 'tickets', 'purchase_history', ['purchase_history_id'], ['id'])
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'created_at')
    op.drop_column('tickets', 'arrival_time')
    op.drop_column('tickets', 'boarding_time')
    op.drop_column('tickets', 'price')
    op.drop_column('tickets', 'seat_number')
    op.drop_column('tickets', 'seat_class')
    op.drop_column('tickets', 'passenger_id')
    op.drop_column('tickets', 'purchase_id')
    op.add_column('purchase_history', sa.Column('dt_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('purchase_history', sa.Column('destiny', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('purchase_history', sa.Column('origin', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('purchase_history', sa.Column('dt_create', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('purchase_history', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchase_history', type_='foreignkey')
    op.create_foreign_key('purchase_history_user_id_fkey', 'purchase_history', 'persons', ['user_id'], ['id'])
    op.alter_column('purchase_history', 'status',
               existing_type=sa.Enum('active', 'planned', 'past', name='purchase_status', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('purchase_history', 'updated_at')
    op.drop_column('purchase_history', 'created_at')
    op.drop_column('purchase_history', 'payment_method')
    op.drop_column('purchase_history', 'total_amount')
    op.drop_column('purchase_history', 'person_id')
    op.add_column('persons', sa.Column('dt_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('dt_birth', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('persons', sa.Column('p_type', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('state', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('persons', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('persons', sa.Column('dt_create', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('persons', 'updated_at')
    op.drop_column('persons', 'created_at')
    op.drop_column('persons', 'person_type')
    op.drop_column('persons', 'status')
    op.drop_column('persons', 'phone_number')
    op.drop_column('persons', 'birth_date')
    op.drop_column('persons', 'full_name')
    op.add_column('flights', sa.Column('f_class', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('arrival', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('t_seats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('dt_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('flights', sa.Column('destiny', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('origin', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('departure', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('a_seats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('dt_create', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('flights', 'updated_at')
    op.drop_column('flights', 'created_at')
    op.drop_column('flights', 'first_seats')
    op.drop_column('flights', 'business_seats')
    op.drop_column('flights', 'economy_seats')
    op.drop_column('flights', 'estimated_arrival')
    op.drop_column('flights', 'departure_time')
    op.drop_column('flights', 'destination_airport')
    op.drop_column('flights', 'destination_city')
    op.drop_column('flights', 'origin_airport')
    op.drop_column('flights', 'origin_city')
    op.drop_column('flights', 'aircraft_model')
    op.add_column('airlines', sa.Column('dt_create', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('airlines', sa.Column('dt_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('airlines', 'updated_at')
    op.drop_column('airlines', 'created_at')
    op.create_table('ticket_passengers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name='ticket_passengers_person_id_fkey'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name='ticket_passengers_ticket_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ticket_passengers_pkey')
    )
    op.create_index('ix_ticket_passengers_id', 'ticket_passengers', ['id'], unique=False)
    op.drop_index(op.f('ix_ticket_status_log_id'), table_name='ticket_status_log')
    op.drop_table('ticket_status_log')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    # ### end Alembic commands ###
