"""change_seat_enum

Revision ID: a3272da0f761
Revises: 8913b06f344c
Create Date: 2025-12-09 20:50:17.004149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3272da0f761'
down_revision: Union[str, None] = '007_enable_unaccent'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seats', 'seat_class',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('economy', 'premium', name='seat_class_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('tickets', 'seat_class',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('economy', 'premium', name='seat_class', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'seat_class',
               existing_type=sa.Enum('economy', 'premium', name='seat_class', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('seats', 'seat_class',
               existing_type=sa.Enum('economy', 'premium', name='seat_class_enum', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
