"""remove_history_purchase

Revision ID: dfd5e10710e3
Revises: 8ec4ed8b1a58
Create Date: 2025-11-17 15:58:13.892169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfd5e10710e3'
down_revision: Union[str, None] = '8ec4ed8b1a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - ajustado para CASCADE ###
    # Use execute to handle errors gracefully
    op.execute("DROP INDEX IF EXISTS ix_purchase_history_id")
    op.execute("DROP TABLE IF EXISTS purchase_history CASCADE")
    op.execute("ALTER TABLE tickets DROP CONSTRAINT IF EXISTS tickets_purchase_id_fkey")
    op.execute("ALTER TABLE tickets DROP COLUMN IF EXISTS purchase_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.add_column('tickets', sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tickets_purchase_id_fkey', 'tickets', 'purchase_history', ['purchase_id'], ['id'])
    op.create_table('purchase_history',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('status', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
        sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
        sa.Column('payment_method', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name='purchase_history_person_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='purchase_history_pkey')
    )
    op.create_index('ix_purchase_history_id', 'purchase_history', ['id'], unique=False)
    # ### end Alembic commands ###
